/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a app_adaptor.h: ../sailfish/iface/org.quickddit.app.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef APP_ADAPTOR_H_1446890706
#define APP_ADAPTOR_H_1446890706

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.quickddit.view
 */
class ViewAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.quickddit.view")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.quickddit.view\">\n"
"    <method name=\"showInbox\"/>\n"
"    <method name=\"showInboxFor\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"target\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ViewAdaptor(QObject *parent);
    virtual ~ViewAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void showInbox();
    void showInboxFor(const QString &target);
Q_SIGNALS: // SIGNALS
};

#endif
