/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p app_interface.h: ../sailfish/iface/org.quickddit.app.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef APP_INTERFACE_H_1446890660
#define APP_INTERFACE_H_1446890660

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.quickddit.view
 */
class OrgQuickdditViewInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.quickddit.view"; }

public:
    OrgQuickdditViewInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgQuickdditViewInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> showInbox()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("showInbox"), argumentList);
    }

    inline QDBusPendingReply<> showInboxFor(const QString &target)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(target);
        return asyncCallWithArgumentList(QLatin1String("showInboxFor"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace quickddit {
    typedef ::OrgQuickdditViewInterface view;
  }
}
#endif
