/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i app_adaptor.h -a :app_adaptor.cpp ../sailfish/iface/org.quickddit.app.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "app_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ViewAdaptor
 */

ViewAdaptor::ViewAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ViewAdaptor::~ViewAdaptor()
{
    // destructor
}

void ViewAdaptor::showInbox()
{
    // handle method call org.quickddit.view.showInbox
    QMetaObject::invokeMethod(parent(), "showInbox");
}

void ViewAdaptor::showInboxFor(const QString &target)
{
    // handle method call org.quickddit.view.showInboxFor
    QMetaObject::invokeMethod(parent(), "showInboxFor", Q_ARG(QString, target));
}

