/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i app_interface.h -p :app_interface.cpp ../sailfish/iface/org.quickddit.app.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "app_interface.h"
/*
 * Implementation of interface class OrgQuickdditViewInterface
 */

OrgQuickdditViewInterface::OrgQuickdditViewInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgQuickdditViewInterface::~OrgQuickdditViewInterface()
{
}

